// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VassaSpraket_TW.Data;

#nullable disable

namespace VassaSpraket_TW.Data.Migrations
{
    [DbContext(typeof(VassaSpraket_TWDbContext))]
    [Migration("20240118095919_insert_data_hotspot")]
    partial class insert_data_hotspot
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VassaSpraket_TW.Data.Models.Chapters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ChapterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("VassaSpraket_TW.Data.Models.Hotspot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CroppedPdfPageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Label_Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label_Left")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label_Top")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label_Width")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<int>("PageTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("PopupSortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PageTemplateId");

                    b.ToTable("Hotspot", (string)null);
                });

            modelBuilder.Entity("VassaSpraket_TW.Data.Models.PageTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("CroppedPdfSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdfSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailImg")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PageTemplate", (string)null);
                });

            modelBuilder.Entity("VassaSpraket_TW.Data.Models.Hotspot", b =>
                {
                    b.HasOne("VassaSpraket_TW.Data.Models.PageTemplate", null)
                        .WithMany("Rows")
                        .HasForeignKey("PageTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VassaSpraket_TW.Data.Models.PageTemplate", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
